#!/bin/dash

# check for .shrug repository exists
if test ! -d ".shrug"
then
	echo "$0: error: no .shrug directory containing shrug repository exists"
	exit 1
fi

if ! [ $# -eq 1 ]
then 
	echo "Usage:$0 branch-name"	
    exit 1
fi


echo $1 > .shrug/branches/current.txt
echo "Switched to branch '$1'"
