#!/bin/dash

# check for .shrug repository exists
if test ! -d ".shrug"
then
	echo "$0: error: no .shrug directory containing shrug repository exists"
	exit 1
fi

# switch to current branch
branch="$(cat .shrug/branches/current.txt)"

if test ! "$(ls .shrug/branches/$branch)"
then
    echo "$0: error: your current branch '$branch' does not have any commits yet"
    exit 1
fi

cat ".shrug/branches/$branch/.log.txt"
