#!/bin/dash

# check for .shrug repository exists
if test ! -d ".shrug"
then
	echo "$0: error: no .shrug directory containing shrug repository exists"
	exit 1
fi

if [ $# -lt 2 ]
then 
	echo "Usage:$0 [-a] -m message"	
    exit 1
fi

# switch to current branch
branch="$(cat .shrug/branches/current.txt)"

empty_deletelist()
{
	rm -f ".shrug/index/deletelist"
	touch ".shrug/index/deletelist"
}

if [ "$1" = "-a" ]
then
	for filename in $(ls -la .shrug/index|egrep '^-'|sed 's/.*:[0-9][0-9] //'|egrep -v "^deletelist$")
	do
		if test -e $filename
		then
			shrug-add $filename
		else
			rm .shrug/index/$filename
		fi
	done
fi



if [ "$1" = "-m" ] || [ "$2" = "-m" ]
then
	# if index is empty 
	if [ -z "$(ls .shrug/index/|egrep -v "deletelist")" ]
	then
		
		if [ -z "$(cat ".shrug/index/deletelist")" ];then
			echo "nothing to commit"
			exit 0
		elif  [ -z "$(head -1 ".shrug/branches/$branch/.log.txt"|cut -d' ' -f1)" ];then
			echo "nothing to commit"
			exit 0
		fi
	fi	
	
	
	if [ $(head -1 ".shrug/branches/$branch/.log.txt"|cut -d' ' -f1) ]
	then
		commit=$(( $(head -1 ".shrug/branches/$branch/.log.txt"|cut -d' ' -f1) ))
		newcommit=$(( $commit + 1 ))
	else
		# initial commit
		commit=0

		for filename in $(ls -la .shrug/index|egrep '^-'|sed 's/.*:[0-9][0-9] //'|egrep -v "^deletelist$")
		do
			cp -f ".shrug/index/$filename" ".shrug/branches/$branch/$filename.$commit" > /dev/null 2>&1
		done
		
		echo "$commit $2" | cat - ".shrug/branches/$branch/.log.txt"  > temp && mv temp ".shrug/branches/$branch/.log.txt"
		echo "Committed as commit $commit"

		exit 0
	fi
	
	# commiting each file to current branch from index
	flag=0
	if ! [ -z "$(cat ".shrug/index/deletelist")" ];then
		flag=1
		for delfile in $(cat ".shrug/index/deletelist")
		do
			for filename in $(ls -la .shrug/index|egrep '^-'|sed 's/.*:[0-9][0-9] //'|egrep -v "^deletelist$")
			do
				if [ "$delfile" != "$filename" ];then
					cp -f ".shrug/index/$filename" ".shrug/branches/$branch/$filename.$newcommit" > /dev/null 2>&1

				fi
			done
		done	
	fi
	
	for filename in $(ls -la .shrug/index|egrep '^-'|sed 's/.*:[0-9][0-9] //'|egrep -v "^deletelist$")
	do	
		# empty files adding
		if [ -s .shrug/index/$filename ]
		then
			if [ $(ls -la .shrug/branches/$branch|grep '^-'|sed 's/.*:[0-9][0-9] //'|egrep "^$filename.*$"|wc -l) -eq 0 ];then
				cp -f ".shrug/index/$filename" ".shrug/branches/$branch/$filename.$newcommit" > /dev/null 2>&1
				flag=1	
			fi
		fi
		
		
		if ! [ -z "$(diff -N ".shrug/index/$filename" ".shrug/branches/$branch/$filename.$commit")" ];then
			# commiting with commit id snapshots if there is difference
			cp -f ".shrug/index/$filename" ".shrug/branches/$branch/$filename.$newcommit" > /dev/null 2>&1
			flag=1
		else
			if [ -z "$(ls -1 ".shrug/branches/$branch/"|egrep "$filename")" ];then
				latest=0
			else
				latest="$(( $(ls -1 ".shrug/branches/$branch/"|egrep "$filename"|tr '.' '-'|sed s/.*-//|sort -n|tail -1) ))"
			fi
			
			if ! [ -e ".shrug/branches/$branch/$filename.$commit" ];then
				if [ -e ".shrug/branches/$branch/$filename.$latest" ];then
					cp -f ".shrug/index/$filename" ".shrug/branches/$branch/$filename.$newcommit" > /dev/null 2>&1
					flag=1
				fi
			fi
			
			if [ $(( $commit - $latest )) -gt 1 ];then
				cp -f ".shrug/index/$filename" ".shrug/branches/$branch/$filename.$newcommit" > /dev/null 2>&1
				flag=1
			fi
			

		fi
		
	done
	
	# no difference in any file no commit
	if [ $flag -eq 0 ]
	then
		echo "nothing to commit"
		exit 1
	else
		echo "$newcommit $2" | cat - ".shrug/branches/$branch/.log.txt"  > temp && mv temp ".shrug/branches/$branch/.log.txt"
		echo "Committed as commit $newcommit"
		empty_deletelist
	fi
	
fi

